version: '3.8'
services:
  db:
    image: postgres:13
    container_name: postgres
    environment:
      POSTGRES_DB: petShelter_db
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
    ports:
      - "5434:5432"
    volumes:
      - petShelter_data:/var/lib/postgresql/data

volumes:
  petShelter_data: