version: '3.8'
services:
  db:
    image: postgres:13
    container_name: postgres
    environment:
      POSTGRES_DB: petShelter_db
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
    ports:
      - "5434:5432"
    volumes:
      - petShelter_data:/var/lib/postgresql/data

  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "5672:5672"   #Porta de comunicação AMQP (Spring usa essa)
      - "15672:15672" #Painel web de administração
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest

volumes:
  petShelter_data: